/**
 * Cookie Manager
 * 
 * Handles cookie storage, persistence, and automatic management.
 * Supports Netscape Cookie Jar format for compatibility.
 */

import fs from 'fs';
import { parseCookie } from '../http/response.js';

/**
 * Cookie jar for session cookie storage.
 * Respects domain, path, and secure when building Cookie header via getCookieHeader().
 * Supports Netscape cookie file format for save/load.
 */
export class CookieJar {
    constructor() {
        /** @type {Map<string, object>} */
        this.cookies = new Map();
    }

    /**
     * Add a cookie from Set-Cookie header
     * @param {string} setCookieValue - Set-Cookie header value
     * @param {string} defaultDomain - Default domain if not specified
     */
    add(setCookieValue, defaultDomain = '') {
        const cookie = parseCookie(setCookieValue);

        if (!cookie.domain) {
            cookie.domain = defaultDomain;
        }

        // Check expiration
        if (cookie.expires && cookie.expires < new Date()) {
            this.cookies.delete(cookie.name);
            return;
        }

        if (cookie.maxAge !== null && cookie.maxAge <= 0) {
            this.cookies.delete(cookie.name);
            return;
        }

        this.cookies.set(cookie.name, cookie);
    }

    /**
     * Add multiple cookies from response
     * @param {string[]} setCookieHeaders - Array of Set-Cookie values
     * @param {string} defaultDomain - Default domain
     */
    addFromResponse(setCookieHeaders, defaultDomain = '') {
        for (const header of setCookieHeaders) {
            this.add(header, defaultDomain);
        }
    }

    /**
     * Get cookie header string for a request
     * @param {string} domain - Target domain
     * @param {string} path - Target path
     * @param {boolean} secure - Is secure connection
     * @returns {string}
     */
    getCookieHeader(domain = '', path = '/', secure = false) {
        const validCookies = [];
        const now = new Date();

        for (const [name, cookie] of this.cookies) {
            // Check expiration
            if (cookie.expires && cookie.expires < now) {
                this.cookies.delete(name);
                continue;
            }

            // Check domain match
            if (cookie.domain && domain) {
                const cookieDomain = cookie.domain.startsWith('.')
                    ? cookie.domain.substring(1)
                    : cookie.domain;

                if (!domain.endsWith(cookieDomain) && domain !== cookieDomain) {
                    continue;
                }
            }

            // Check path match
            if (cookie.path && path) {
                if (!path.startsWith(cookie.path)) {
                    continue;
                }
            }

            // Check secure flag
            if (cookie.secure && !secure) {
                continue;
            }

            validCookies.push(`${cookie.name}=${cookie.value}`);
        }

        return validCookies.join('; ');
    }

    /**
     * Get a specific cookie value
     * @param {string} name - Cookie name
     * @returns {string|null}
     */
    get(name) {
        const cookie = this.cookies.get(name);
        return cookie ? cookie.value : null;
    }

    /**
     * Set a cookie manually
     * @param {string} name - Cookie name
     * @param {string} value - Cookie value
     * @param {object} options - Cookie options
     */
    set(name, value, options = {}) {
        this.cookies.set(name, {
            name,
            value,
            domain: options.domain || '',
            path: options.path || '/',
            secure: options.secure || false,
            httpOnly: options.httpOnly || false,
            expires: options.expires || null,
            maxAge: options.maxAge || null,
            sameSite: options.sameSite || '',
        });
    }

    /**
     * Remove a cookie
     * @param {string} name - Cookie name
     */
    delete(name) {
        this.cookies.delete(name);
    }

    /**
     * Clear all cookies
     */
    clear() {
        this.cookies.clear();
    }

    /**
     * Get all cookies as object
     * @returns {Object}
     */
    toObject() {
        const result = {};
        for (const [name, cookie] of this.cookies) {
            result[name] = cookie.value;
        }
        return result;
    }

    /**
     * Get number of cookies
     * @returns {number}
     */
    get size() {
        return this.cookies.size;
    }

    /**
     * Save cookies to file (Netscape Cookie Jar format)
     * @param {string} filePath - Output file path
     */
    save(filePath) {
        let content = '# Netscape HTTP Cookie File\n';
        content += '# Generated by jsploit\n';
        content += `# Date: ${new Date().toISOString()}\n\n`;

        for (const [, cookie] of this.cookies) {
            const domain = cookie.domain || '.';
            const tailmatch = domain.startsWith('.') ? 'TRUE' : 'FALSE';
            const secure = cookie.secure ? 'TRUE' : 'FALSE';

            let expires = '0';
            if (cookie.expires) {
                expires = Math.floor(cookie.expires.getTime() / 1000).toString();
            } else if (cookie.maxAge) {
                expires = (Math.floor(Date.now() / 1000) + cookie.maxAge).toString();
            }

            content += `${domain}\t${tailmatch}\t${cookie.path}\t${secure}\t${expires}\t${cookie.name}\t${cookie.value}\n`;
        }

        fs.writeFileSync(filePath, content);
    }

    /**
     * Load cookies from file (Netscape Cookie Jar format)
     * @param {string} filePath - Input file path
     */
    load(filePath) {
        if (!fs.existsSync(filePath)) {
            return;
        }

        const content = fs.readFileSync(filePath, 'utf-8');
        const lines = content.split('\n');

        for (const line of lines) {
            // Skip comments and empty lines
            if (line.startsWith('#') || line.trim() === '') {
                continue;
            }

            const parts = line.split('\t');
            if (parts.length >= 7) {
                const domain = parts[0];
                const path = parts[2];
                const secure = parts[3] === 'TRUE';
                const expires = parseInt(parts[4]);
                const name = parts[5];
                const value = parts[6];

                this.set(name, value, {
                    domain,
                    path,
                    secure,
                    expires: expires > 0 ? new Date(expires * 1000) : null,
                });
            }
        }
    }
}

/**
 * Create a new cookie jar
 * @returns {CookieJar}
 */
export function createCookieJar() {
    return new CookieJar();
}

